name: PR Comment

on: workflow_dispatch
  #pull_request_target:
  #  types:
  #    - opened

jobs:
    build:
        name: Comment a pull_request
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Comment a pull_request
              uses: mb2dev/github-action-comment-pull-request@1.0.0
              with:
                message:  |
                    Thank you for your PR! The following checklist can be used to ensure that the PR is as helpful as possible and to help maintain the quality of the project.

                    *This checklist is experimental and can be ignored if you wish.
                    Feel free to ask if anything is unclear, or make suggestions.*

                    **Documentation**

                    - [ ] I have updated the module doc-strings of any modules modified, or this comment is not relevant.
                    - [ ] I created a new module doc-string for any new modules created, including an overall description of the module and the main results, or this comment is not relevant.
                    - [ ] I have changed all doc-string occurances of decleration names which I have changed, or this comment is not relevant.
                    - [ ] For definitions and key theorems I have added, I have added an english-readable statement of the result, which is as self-contained as possible, and where appropriate contain a readable UTF-8 version of the result.
                    - [ ] Where appropriate and helpful I have included references to the original source of results in the module doc-string.

                    **Lemmas and theorems**

                    - [ ] I have ensured that the `theorem` key word is reserved for *important* theorems, and `lemma` is used for everything else.
                    - [ ] I have ensured that no lemmas or definitions are duplications of other results.

                    **Layout**

                    - [ ] I have ensured that results are in the appropriate modules.

                    **Usage of AI**

                    Please tick one that applies to this PR:

                    - [ ] I have not used any AI to generate code.
                    - [ ] I have used basic AI coding assistance (e.g. Copilot) to generate repeative bits of code, but the lemmas and definitions are my own.
                    - [ ] I used AI to generate the structure of the code and/or guide its organization, but I have checked it for corectness.
                    - [ ] Other (please specify with a comment).


                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
